
namespace CapaPresentaciones
{
    partial class P_HistorialAsistenciasDocentes
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

		#region Windows Form Designer generated code

		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(P_HistorialAsistenciasDocentes));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle4 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            this.lblTitulo = new Bunifu.UI.WinForms.BunifuLabel();
            this.btnCerrar = new Bunifu.UI.WinForms.BunifuImageButton();
            this.txtBuscar = new Bunifu.UI.WinForms.BunifuTextBox();
            this.dgvDatos = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.btnEditar = new System.Windows.Forms.DataGridViewImageColumn();
            this.sbDatos = new Bunifu.UI.WinForms.BunifuVScrollBar();
            this.pnContenedor = new Bunifu.UI.WinForms.BunifuPanel();
            this.btnAgregarD = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.Bordeado = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.txtInicioHoras = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lblHoraInicio = new Bunifu.UI.WinForms.BunifuLabel();
            this.txtInicioMinutos = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lblPuntosInicio = new Bunifu.UI.WinForms.BunifuLabel();
            this.lblPuntosFin = new Bunifu.UI.WinForms.BunifuLabel();
            this.txtFinMinutos = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtFinHoras = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lblHoraFin = new Bunifu.UI.WinForms.BunifuLabel();
            this.btnCambiar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            ((System.ComponentModel.ISupportInitialize)(this.dgvDatos)).BeginInit();
            this.pnContenedor.SuspendLayout();
            this.SuspendLayout();
            // 
            // lblTitulo
            // 
            this.lblTitulo.AllowParentOverrides = false;
            this.lblTitulo.AutoEllipsis = false;
            this.lblTitulo.AutoSize = false;
            this.lblTitulo.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(104)))), ((int)(((byte)(13)))), ((int)(((byte)(15)))));
            this.lblTitulo.Cursor = System.Windows.Forms.Cursors.Default;
            this.lblTitulo.CursorType = System.Windows.Forms.Cursors.Default;
            this.lblTitulo.Dock = System.Windows.Forms.DockStyle.Top;
            this.lblTitulo.Font = new System.Drawing.Font("Montserrat Alternates", 12F);
            this.lblTitulo.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(158)))), ((int)(((byte)(31)))));
            this.lblTitulo.Location = new System.Drawing.Point(0, 0);
            this.lblTitulo.Name = "lblTitulo";
            this.lblTitulo.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblTitulo.Size = new System.Drawing.Size(791, 46);
            this.lblTitulo.TabIndex = 1;
            this.lblTitulo.Text = "Historial de Asistencias Diarias de Docentes";
            this.lblTitulo.TextAlignment = System.Drawing.ContentAlignment.MiddleCenter;
            this.lblTitulo.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // btnCerrar
            // 
            this.btnCerrar.ActiveImage = null;
            this.btnCerrar.AllowAnimations = true;
            this.btnCerrar.AllowBuffering = false;
            this.btnCerrar.AllowToggling = false;
            this.btnCerrar.AllowZooming = true;
            this.btnCerrar.AllowZoomingOnFocus = false;
            this.btnCerrar.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnCerrar.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(104)))), ((int)(((byte)(13)))), ((int)(((byte)(15)))));
            this.btnCerrar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnCerrar.ErrorImage = null;
            this.btnCerrar.FadeWhenInactive = false;
            this.btnCerrar.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            this.btnCerrar.Image = global::CapaPresentaciones.Properties.Resources.Cerrar;
            this.btnCerrar.ImageActive = null;
            this.btnCerrar.ImageLocation = null;
            this.btnCerrar.ImageMargin = 10;
            this.btnCerrar.ImageSize = new System.Drawing.Size(20, 20);
            this.btnCerrar.ImageZoomSize = new System.Drawing.Size(30, 30);
            this.btnCerrar.InitialImage = null;
            this.btnCerrar.Location = new System.Drawing.Point(753, 7);
            this.btnCerrar.Name = "btnCerrar";
            this.btnCerrar.Rotation = 0;
            this.btnCerrar.ShowActiveImage = true;
            this.btnCerrar.ShowCursorChanges = true;
            this.btnCerrar.ShowImageBorders = true;
            this.btnCerrar.ShowSizeMarkers = false;
            this.btnCerrar.Size = new System.Drawing.Size(30, 30);
            this.btnCerrar.TabIndex = 11;
            this.btnCerrar.ToolTipText = "";
            this.btnCerrar.WaitOnLoad = false;
            this.btnCerrar.Zoom = 10;
            this.btnCerrar.ZoomSpeed = 10;
            this.btnCerrar.Click += new System.EventHandler(this.btnCerrar_Click);
            // 
            // txtBuscar
            // 
            this.txtBuscar.AcceptsReturn = false;
            this.txtBuscar.AcceptsTab = false;
            this.txtBuscar.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.txtBuscar.AnimationSpeed = 200;
            this.txtBuscar.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtBuscar.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtBuscar.AutoSizeHeight = true;
            this.txtBuscar.BackColor = System.Drawing.Color.White;
            this.txtBuscar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtBuscar.BackgroundImage")));
            this.txtBuscar.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(158)))), ((int)(((byte)(31)))));
            this.txtBuscar.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtBuscar.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(158)))), ((int)(((byte)(31)))));
            this.txtBuscar.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(104)))), ((int)(((byte)(13)))), ((int)(((byte)(15)))));
            this.txtBuscar.BorderRadius = 1;
            this.txtBuscar.BorderThickness = 1;
            this.txtBuscar.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtBuscar.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtBuscar.DefaultFont = new System.Drawing.Font("Montserrat Alternates", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtBuscar.DefaultText = "";
            this.txtBuscar.FillColor = System.Drawing.Color.White;
            this.txtBuscar.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(104)))), ((int)(((byte)(13)))), ((int)(((byte)(15)))));
            this.txtBuscar.HideSelection = true;
            this.txtBuscar.IconLeft = global::CapaPresentaciones.Properties.Resources.Buscar_2;
            this.txtBuscar.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtBuscar.IconPadding = 8;
            this.txtBuscar.IconRight = null;
            this.txtBuscar.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtBuscar.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.txtBuscar.Lines = new string[0];
            this.txtBuscar.Location = new System.Drawing.Point(10, 95);
            this.txtBuscar.Margin = new System.Windows.Forms.Padding(0);
            this.txtBuscar.MaxLength = 32767;
            this.txtBuscar.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtBuscar.Modified = false;
            this.txtBuscar.Multiline = false;
            this.txtBuscar.Name = "txtBuscar";
            stateProperties1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(158)))), ((int)(((byte)(31)))));
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtBuscar.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtBuscar.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(158)))), ((int)(((byte)(31)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtBuscar.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(104)))), ((int)(((byte)(13)))), ((int)(((byte)(15)))));
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(104)))), ((int)(((byte)(13)))), ((int)(((byte)(15)))));
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtBuscar.OnIdleState = stateProperties4;
            this.txtBuscar.Padding = new System.Windows.Forms.Padding(3);
            this.txtBuscar.PasswordChar = '\0';
            this.txtBuscar.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.txtBuscar.PlaceholderText = "Buscar";
            this.txtBuscar.ReadOnly = false;
            this.txtBuscar.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtBuscar.SelectedText = "";
            this.txtBuscar.SelectionLength = 0;
            this.txtBuscar.SelectionStart = 0;
            this.txtBuscar.ShortcutsEnabled = true;
            this.txtBuscar.Size = new System.Drawing.Size(773, 40);
            this.txtBuscar.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.txtBuscar.TabIndex = 12;
            this.txtBuscar.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtBuscar.TextMarginBottom = 0;
            this.txtBuscar.TextMarginLeft = 7;
            this.txtBuscar.TextMarginTop = 0;
            this.txtBuscar.TextPlaceholder = "Buscar";
            this.txtBuscar.UseSystemPasswordChar = false;
            this.txtBuscar.WordWrap = true;
            this.txtBuscar.TextChanged += new System.EventHandler(this.txtBuscar_TextChanged);
            // 
            // dgvDatos
            // 
            this.dgvDatos.AllowCustomTheming = true;
            this.dgvDatos.AllowUserToAddRows = false;
            this.dgvDatos.AllowUserToDeleteRows = false;
            this.dgvDatos.AllowUserToOrderColumns = true;
            this.dgvDatos.AllowUserToResizeRows = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(185)))), ((int)(((byte)(142)))), ((int)(((byte)(142)))));
            dataGridViewCellStyle1.Font = new System.Drawing.Font("Montserrat Alternates", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(104)))), ((int)(((byte)(13)))), ((int)(((byte)(15)))));
            this.dgvDatos.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.dgvDatos.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.dgvDatos.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvDatos.BackgroundColor = System.Drawing.Color.White;
            this.dgvDatos.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.dgvDatos.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.dgvDatos.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(104)))), ((int)(((byte)(13)))), ((int)(((byte)(15)))));
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Montserrat Alternates", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(158)))), ((int)(((byte)(31)))));
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(104)))), ((int)(((byte)(13)))), ((int)(((byte)(15)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(104)))), ((int)(((byte)(13)))), ((int)(((byte)(15)))));
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dgvDatos.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.dgvDatos.ColumnHeadersHeight = 28;
            this.dgvDatos.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
            this.dgvDatos.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] {
            this.btnEditar});
            this.dgvDatos.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(185)))), ((int)(((byte)(142)))), ((int)(((byte)(142)))));
            this.dgvDatos.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Montserrat Alternates", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.dgvDatos.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(104)))), ((int)(((byte)(13)))), ((int)(((byte)(15)))));
            this.dgvDatos.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(158)))), ((int)(((byte)(31)))));
            this.dgvDatos.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(104)))), ((int)(((byte)(13)))), ((int)(((byte)(15)))));
            this.dgvDatos.CurrentTheme.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(104)))), ((int)(((byte)(13)))), ((int)(((byte)(15)))));
            this.dgvDatos.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(179)))), ((int)(((byte)(179)))));
            this.dgvDatos.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(104)))), ((int)(((byte)(13)))), ((int)(((byte)(15)))));
            this.dgvDatos.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Montserrat Alternates", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.dgvDatos.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(158)))), ((int)(((byte)(31)))));
            this.dgvDatos.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(104)))), ((int)(((byte)(13)))), ((int)(((byte)(15)))));
            this.dgvDatos.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(104)))), ((int)(((byte)(13)))), ((int)(((byte)(15)))));
            this.dgvDatos.CurrentTheme.Name = null;
            this.dgvDatos.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(179)))), ((int)(((byte)(179)))));
            this.dgvDatos.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Montserrat Alternates", 12F);
            this.dgvDatos.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(104)))), ((int)(((byte)(13)))), ((int)(((byte)(15)))));
            this.dgvDatos.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(158)))), ((int)(((byte)(31)))));
            this.dgvDatos.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(104)))), ((int)(((byte)(13)))), ((int)(((byte)(15)))));
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(179)))), ((int)(((byte)(179)))));
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Montserrat Alternates", 12F);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(104)))), ((int)(((byte)(13)))), ((int)(((byte)(15)))));
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(158)))), ((int)(((byte)(31)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(104)))), ((int)(((byte)(13)))), ((int)(((byte)(15)))));
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dgvDatos.DefaultCellStyle = dataGridViewCellStyle3;
            this.dgvDatos.EnableHeadersVisualStyles = false;
            this.dgvDatos.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(179)))), ((int)(((byte)(179)))));
            this.dgvDatos.HeaderBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(104)))), ((int)(((byte)(13)))), ((int)(((byte)(15)))));
            this.dgvDatos.HeaderBgColor = System.Drawing.Color.Empty;
            this.dgvDatos.HeaderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(158)))), ((int)(((byte)(31)))));
            this.dgvDatos.Location = new System.Drawing.Point(10, 145);
            this.dgvDatos.MultiSelect = false;
            this.dgvDatos.Name = "dgvDatos";
            this.dgvDatos.ReadOnly = true;
            dataGridViewCellStyle4.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle4.BackColor = System.Drawing.SystemColors.Control;
            dataGridViewCellStyle4.Font = new System.Drawing.Font("Montserrat Alternates", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle4.ForeColor = System.Drawing.SystemColors.WindowText;
            dataGridViewCellStyle4.SelectionBackColor = System.Drawing.SystemColors.Highlight;
            dataGridViewCellStyle4.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle4.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dgvDatos.RowHeadersDefaultCellStyle = dataGridViewCellStyle4;
            this.dgvDatos.RowHeadersVisible = false;
            this.dgvDatos.RowHeadersWidth = 28;
            this.dgvDatos.RowHeadersWidthSizeMode = System.Windows.Forms.DataGridViewRowHeadersWidthSizeMode.DisableResizing;
            this.dgvDatos.RowTemplate.DefaultCellStyle.Font = new System.Drawing.Font("Montserrat Alternates", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.dgvDatos.RowTemplate.Height = 26;
            this.dgvDatos.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.dgvDatos.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.CellSelect;
            this.dgvDatos.Size = new System.Drawing.Size(773, 298);
            this.dgvDatos.TabIndex = 14;
            this.dgvDatos.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Maroon;
            this.dgvDatos.CellClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.dgvDatos_CellClick);
            // 
            // btnEditar
            // 
            this.btnEditar.HeaderText = "Editar";
            this.btnEditar.Image = global::CapaPresentaciones.Properties.Resources.Editar_2;
            this.btnEditar.ImageLayout = System.Windows.Forms.DataGridViewImageCellLayout.Zoom;
            this.btnEditar.Name = "btnEditar";
            this.btnEditar.ReadOnly = true;
            // 
            // sbDatos
            // 
            this.sbDatos.AllowCursorChanges = true;
            this.sbDatos.AllowHomeEndKeysDetection = false;
            this.sbDatos.AllowIncrementalClickMoves = true;
            this.sbDatos.AllowMouseDownEffects = true;
            this.sbDatos.AllowMouseHoverEffects = true;
            this.sbDatos.AllowScrollingAnimations = true;
            this.sbDatos.AllowScrollKeysDetection = true;
            this.sbDatos.AllowScrollOptionsMenu = true;
            this.sbDatos.AllowShrinkingOnFocusLost = false;
            this.sbDatos.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.sbDatos.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(104)))), ((int)(((byte)(13)))), ((int)(((byte)(15)))));
            this.sbDatos.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("sbDatos.BackgroundImage")));
            this.sbDatos.BindingContainer = null;
            this.sbDatos.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(104)))), ((int)(((byte)(13)))), ((int)(((byte)(15)))));
            this.sbDatos.BorderRadius = 0;
            this.sbDatos.BorderThickness = 1;
            this.sbDatos.DurationBeforeShrink = 2000;
            this.sbDatos.LargeChange = 10;
            this.sbDatos.Location = new System.Drawing.Point(773, 171);
            this.sbDatos.Maximum = 100;
            this.sbDatos.Minimum = 0;
            this.sbDatos.MinimumThumbLength = 18;
            this.sbDatos.Name = "sbDatos";
            this.sbDatos.OnDisable.ScrollBarBorderColor = System.Drawing.Color.Silver;
            this.sbDatos.OnDisable.ScrollBarColor = System.Drawing.Color.Transparent;
            this.sbDatos.OnDisable.ThumbColor = System.Drawing.Color.Silver;
            this.sbDatos.ScrollBarBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(104)))), ((int)(((byte)(13)))), ((int)(((byte)(15)))));
            this.sbDatos.ScrollBarColor = System.Drawing.Color.FromArgb(((int)(((byte)(104)))), ((int)(((byte)(13)))), ((int)(((byte)(15)))));
            this.sbDatos.ShrinkSizeLimit = 3;
            this.sbDatos.Size = new System.Drawing.Size(10, 272);
            this.sbDatos.SmallChange = 1;
            this.sbDatos.TabIndex = 16;
            this.sbDatos.ThumbColor = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(158)))), ((int)(((byte)(31)))));
            this.sbDatos.ThumbLength = 26;
            this.sbDatos.ThumbMargin = 1;
            this.sbDatos.ThumbStyle = Bunifu.UI.WinForms.BunifuVScrollBar.ThumbStyles.Inset;
            this.sbDatos.Value = 0;
            // 
            // pnContenedor
            // 
            this.pnContenedor.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.pnContenedor.BackgroundColor = System.Drawing.Color.White;
            this.pnContenedor.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("pnContenedor.BackgroundImage")));
            this.pnContenedor.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.pnContenedor.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(104)))), ((int)(((byte)(13)))), ((int)(((byte)(15)))));
            this.pnContenedor.BorderRadius = 20;
            this.pnContenedor.BorderThickness = 1;
            this.pnContenedor.Controls.Add(this.btnCambiar);
            this.pnContenedor.Controls.Add(this.lblPuntosFin);
            this.pnContenedor.Controls.Add(this.txtFinMinutos);
            this.pnContenedor.Controls.Add(this.txtFinHoras);
            this.pnContenedor.Controls.Add(this.lblHoraFin);
            this.pnContenedor.Controls.Add(this.lblPuntosInicio);
            this.pnContenedor.Controls.Add(this.txtInicioMinutos);
            this.pnContenedor.Controls.Add(this.txtInicioHoras);
            this.pnContenedor.Controls.Add(this.lblHoraInicio);
            this.pnContenedor.Controls.Add(this.sbDatos);
            this.pnContenedor.Controls.Add(this.btnAgregarD);
            this.pnContenedor.Controls.Add(this.btnCerrar);
            this.pnContenedor.Controls.Add(this.dgvDatos);
            this.pnContenedor.Controls.Add(this.txtBuscar);
            this.pnContenedor.Controls.Add(this.lblTitulo);
            this.pnContenedor.Location = new System.Drawing.Point(6, 5);
            this.pnContenedor.Name = "pnContenedor";
            this.pnContenedor.ShowBorders = true;
            this.pnContenedor.Size = new System.Drawing.Size(791, 453);
            this.pnContenedor.TabIndex = 17;
            // 
            // btnAgregarD
            // 
            this.btnAgregarD.AllowAnimations = true;
            this.btnAgregarD.AllowMouseEffects = true;
            this.btnAgregarD.AllowToggling = false;
            this.btnAgregarD.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.btnAgregarD.AnimationSpeed = 200;
            this.btnAgregarD.AutoGenerateColors = false;
            this.btnAgregarD.AutoRoundBorders = false;
            this.btnAgregarD.AutoSizeLeftIcon = true;
            this.btnAgregarD.AutoSizeRightIcon = true;
            this.btnAgregarD.BackColor = System.Drawing.Color.Transparent;
            this.btnAgregarD.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(104)))), ((int)(((byte)(13)))), ((int)(((byte)(15)))));
            this.btnAgregarD.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnAgregarD.BackgroundImage")));
            this.btnAgregarD.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnAgregarD.ButtonText = "Agregar";
            this.btnAgregarD.ButtonTextMarginLeft = 0;
            this.btnAgregarD.ColorContrastOnClick = 45;
            this.btnAgregarD.ColorContrastOnHover = 45;
            this.btnAgregarD.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnAgregarD.CustomizableEdges = borderEdges2;
            this.btnAgregarD.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnAgregarD.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAgregarD.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAgregarD.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAgregarD.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnAgregarD.Font = new System.Drawing.Font("Montserrat Alternates", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnAgregarD.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(158)))), ((int)(((byte)(31)))));
            this.btnAgregarD.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnAgregarD.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnAgregarD.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnAgregarD.IconMarginLeft = 11;
            this.btnAgregarD.IconPadding = 10;
            this.btnAgregarD.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnAgregarD.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnAgregarD.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnAgregarD.IconSize = 25;
            this.btnAgregarD.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(158)))), ((int)(((byte)(31)))));
            this.btnAgregarD.IdleBorderRadius = 15;
            this.btnAgregarD.IdleBorderThickness = 1;
            this.btnAgregarD.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(104)))), ((int)(((byte)(13)))), ((int)(((byte)(15)))));
            this.btnAgregarD.IdleIconLeftImage = global::CapaPresentaciones.Properties.Resources.Agregar;
            this.btnAgregarD.IdleIconRightImage = null;
            this.btnAgregarD.IndicateFocus = false;
            this.btnAgregarD.Location = new System.Drawing.Point(623, 53);
            this.btnAgregarD.Name = "btnAgregarD";
            this.btnAgregarD.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAgregarD.OnDisabledState.BorderRadius = 15;
            this.btnAgregarD.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnAgregarD.OnDisabledState.BorderThickness = 1;
            this.btnAgregarD.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAgregarD.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAgregarD.OnDisabledState.IconLeftImage = null;
            this.btnAgregarD.OnDisabledState.IconRightImage = null;
            this.btnAgregarD.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(104)))), ((int)(((byte)(13)))), ((int)(((byte)(15)))));
            this.btnAgregarD.onHoverState.BorderRadius = 15;
            this.btnAgregarD.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnAgregarD.onHoverState.BorderThickness = 1;
            this.btnAgregarD.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(158)))), ((int)(((byte)(31)))));
            this.btnAgregarD.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(104)))), ((int)(((byte)(13)))), ((int)(((byte)(15)))));
            this.btnAgregarD.onHoverState.IconLeftImage = global::CapaPresentaciones.Properties.Resources.Agregar_2;
            this.btnAgregarD.onHoverState.IconRightImage = null;
            this.btnAgregarD.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(158)))), ((int)(((byte)(31)))));
            this.btnAgregarD.OnIdleState.BorderRadius = 15;
            this.btnAgregarD.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnAgregarD.OnIdleState.BorderThickness = 1;
            this.btnAgregarD.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(104)))), ((int)(((byte)(13)))), ((int)(((byte)(15)))));
            this.btnAgregarD.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(158)))), ((int)(((byte)(31)))));
            this.btnAgregarD.OnIdleState.IconLeftImage = global::CapaPresentaciones.Properties.Resources.Agregar;
            this.btnAgregarD.OnIdleState.IconRightImage = null;
            this.btnAgregarD.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(158)))), ((int)(((byte)(31)))));
            this.btnAgregarD.OnPressedState.BorderRadius = 15;
            this.btnAgregarD.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnAgregarD.OnPressedState.BorderThickness = 1;
            this.btnAgregarD.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(104)))), ((int)(((byte)(13)))), ((int)(((byte)(15)))));
            this.btnAgregarD.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(158)))), ((int)(((byte)(31)))));
            this.btnAgregarD.OnPressedState.IconLeftImage = global::CapaPresentaciones.Properties.Resources.Agregar;
            this.btnAgregarD.OnPressedState.IconRightImage = null;
            this.btnAgregarD.Size = new System.Drawing.Size(160, 39);
            this.btnAgregarD.TabIndex = 29;
            this.btnAgregarD.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnAgregarD.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnAgregarD.TextMarginLeft = 0;
            this.btnAgregarD.TextPadding = new System.Windows.Forms.Padding(12, 0, 0, 0);
            this.btnAgregarD.UseDefaultRadiusAndThickness = true;
            this.btnAgregarD.Click += new System.EventHandler(this.btnAgregarD_Click);
            // 
            // Bordeado
            // 
            this.Bordeado.ElipseRadius = 15;
            this.Bordeado.TargetControl = this.pnContenedor;
            // 
            // txtInicioHoras
            // 
            this.txtInicioHoras.AcceptsReturn = false;
            this.txtInicioHoras.AcceptsTab = false;
            this.txtInicioHoras.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.txtInicioHoras.AnimationSpeed = 200;
            this.txtInicioHoras.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtInicioHoras.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtInicioHoras.AutoSizeHeight = true;
            this.txtInicioHoras.BackColor = System.Drawing.Color.White;
            this.txtInicioHoras.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtInicioHoras.BackgroundImage")));
            this.txtInicioHoras.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(158)))), ((int)(((byte)(31)))));
            this.txtInicioHoras.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtInicioHoras.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(158)))), ((int)(((byte)(31)))));
            this.txtInicioHoras.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(104)))), ((int)(((byte)(13)))), ((int)(((byte)(15)))));
            this.txtInicioHoras.BorderRadius = 1;
            this.txtInicioHoras.BorderThickness = 1;
            this.txtInicioHoras.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtInicioHoras.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtInicioHoras.DefaultFont = new System.Drawing.Font("Montserrat Alternates", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtInicioHoras.DefaultText = "";
            this.txtInicioHoras.FillColor = System.Drawing.Color.White;
            this.txtInicioHoras.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(104)))), ((int)(((byte)(13)))), ((int)(((byte)(15)))));
            this.txtInicioHoras.HideSelection = true;
            this.txtInicioHoras.IconLeft = null;
            this.txtInicioHoras.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtInicioHoras.IconPadding = 0;
            this.txtInicioHoras.IconRight = null;
            this.txtInicioHoras.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtInicioHoras.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.txtInicioHoras.Lines = new string[0];
            this.txtInicioHoras.Location = new System.Drawing.Point(114, 52);
            this.txtInicioHoras.Margin = new System.Windows.Forms.Padding(0);
            this.txtInicioHoras.MaxLength = 32767;
            this.txtInicioHoras.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtInicioHoras.Modified = false;
            this.txtInicioHoras.Multiline = false;
            this.txtInicioHoras.Name = "txtInicioHoras";
            stateProperties17.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(158)))), ((int)(((byte)(31)))));
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtInicioHoras.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtInicioHoras.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(158)))), ((int)(((byte)(31)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtInicioHoras.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(104)))), ((int)(((byte)(13)))), ((int)(((byte)(15)))));
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(104)))), ((int)(((byte)(13)))), ((int)(((byte)(15)))));
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtInicioHoras.OnIdleState = stateProperties20;
            this.txtInicioHoras.Padding = new System.Windows.Forms.Padding(3);
            this.txtInicioHoras.PasswordChar = '\0';
            this.txtInicioHoras.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.txtInicioHoras.PlaceholderText = "HH";
            this.txtInicioHoras.ReadOnly = false;
            this.txtInicioHoras.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtInicioHoras.SelectedText = "";
            this.txtInicioHoras.SelectionLength = 0;
            this.txtInicioHoras.SelectionStart = 0;
            this.txtInicioHoras.ShortcutsEnabled = true;
            this.txtInicioHoras.Size = new System.Drawing.Size(46, 40);
            this.txtInicioHoras.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.txtInicioHoras.TabIndex = 50;
            this.txtInicioHoras.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.txtInicioHoras.TextMarginBottom = 0;
            this.txtInicioHoras.TextMarginLeft = 0;
            this.txtInicioHoras.TextMarginTop = 0;
            this.txtInicioHoras.TextPlaceholder = "HH";
            this.txtInicioHoras.UseSystemPasswordChar = false;
            this.txtInicioHoras.WordWrap = true;
            // 
            // lblHoraInicio
            // 
            this.lblHoraInicio.AllowParentOverrides = false;
            this.lblHoraInicio.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.lblHoraInicio.AutoEllipsis = false;
            this.lblHoraInicio.Cursor = System.Windows.Forms.Cursors.Default;
            this.lblHoraInicio.CursorType = System.Windows.Forms.Cursors.Default;
            this.lblHoraInicio.Font = new System.Drawing.Font("Montserrat Alternates", 12F);
            this.lblHoraInicio.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(104)))), ((int)(((byte)(13)))), ((int)(((byte)(15)))));
            this.lblHoraInicio.Location = new System.Drawing.Point(13, 61);
            this.lblHoraInicio.Name = "lblHoraInicio";
            this.lblHoraInicio.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblHoraInicio.Size = new System.Drawing.Size(92, 23);
            this.lblHoraInicio.TabIndex = 51;
            this.lblHoraInicio.Text = "Hora Inicio:";
            this.lblHoraInicio.TextAlignment = System.Drawing.ContentAlignment.MiddleCenter;
            this.lblHoraInicio.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txtInicioMinutos
            // 
            this.txtInicioMinutos.AcceptsReturn = false;
            this.txtInicioMinutos.AcceptsTab = false;
            this.txtInicioMinutos.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.txtInicioMinutos.AnimationSpeed = 200;
            this.txtInicioMinutos.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtInicioMinutos.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtInicioMinutos.AutoSizeHeight = true;
            this.txtInicioMinutos.BackColor = System.Drawing.Color.White;
            this.txtInicioMinutos.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtInicioMinutos.BackgroundImage")));
            this.txtInicioMinutos.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(158)))), ((int)(((byte)(31)))));
            this.txtInicioMinutos.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtInicioMinutos.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(158)))), ((int)(((byte)(31)))));
            this.txtInicioMinutos.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(104)))), ((int)(((byte)(13)))), ((int)(((byte)(15)))));
            this.txtInicioMinutos.BorderRadius = 1;
            this.txtInicioMinutos.BorderThickness = 1;
            this.txtInicioMinutos.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtInicioMinutos.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtInicioMinutos.DefaultFont = new System.Drawing.Font("Montserrat Alternates", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtInicioMinutos.DefaultText = "";
            this.txtInicioMinutos.FillColor = System.Drawing.Color.White;
            this.txtInicioMinutos.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(104)))), ((int)(((byte)(13)))), ((int)(((byte)(15)))));
            this.txtInicioMinutos.HideSelection = true;
            this.txtInicioMinutos.IconLeft = null;
            this.txtInicioMinutos.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtInicioMinutos.IconPadding = 0;
            this.txtInicioMinutos.IconRight = null;
            this.txtInicioMinutos.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtInicioMinutos.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.txtInicioMinutos.Lines = new string[0];
            this.txtInicioMinutos.Location = new System.Drawing.Point(177, 52);
            this.txtInicioMinutos.Margin = new System.Windows.Forms.Padding(0);
            this.txtInicioMinutos.MaxLength = 32767;
            this.txtInicioMinutos.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtInicioMinutos.Modified = false;
            this.txtInicioMinutos.Multiline = false;
            this.txtInicioMinutos.Name = "txtInicioMinutos";
            stateProperties13.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(158)))), ((int)(((byte)(31)))));
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtInicioMinutos.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtInicioMinutos.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(158)))), ((int)(((byte)(31)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtInicioMinutos.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(104)))), ((int)(((byte)(13)))), ((int)(((byte)(15)))));
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(104)))), ((int)(((byte)(13)))), ((int)(((byte)(15)))));
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtInicioMinutos.OnIdleState = stateProperties16;
            this.txtInicioMinutos.Padding = new System.Windows.Forms.Padding(3);
            this.txtInicioMinutos.PasswordChar = '\0';
            this.txtInicioMinutos.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.txtInicioMinutos.PlaceholderText = "MM";
            this.txtInicioMinutos.ReadOnly = false;
            this.txtInicioMinutos.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtInicioMinutos.SelectedText = "";
            this.txtInicioMinutos.SelectionLength = 0;
            this.txtInicioMinutos.SelectionStart = 0;
            this.txtInicioMinutos.ShortcutsEnabled = true;
            this.txtInicioMinutos.Size = new System.Drawing.Size(46, 40);
            this.txtInicioMinutos.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.txtInicioMinutos.TabIndex = 52;
            this.txtInicioMinutos.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.txtInicioMinutos.TextMarginBottom = 0;
            this.txtInicioMinutos.TextMarginLeft = 0;
            this.txtInicioMinutos.TextMarginTop = 0;
            this.txtInicioMinutos.TextPlaceholder = "MM";
            this.txtInicioMinutos.UseSystemPasswordChar = false;
            this.txtInicioMinutos.WordWrap = true;
            // 
            // lblPuntosInicio
            // 
            this.lblPuntosInicio.AllowParentOverrides = false;
            this.lblPuntosInicio.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.lblPuntosInicio.AutoEllipsis = false;
            this.lblPuntosInicio.Cursor = System.Windows.Forms.Cursors.Default;
            this.lblPuntosInicio.CursorType = System.Windows.Forms.Cursors.Default;
            this.lblPuntosInicio.Font = new System.Drawing.Font("Montserrat Alternates", 12F);
            this.lblPuntosInicio.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(104)))), ((int)(((byte)(13)))), ((int)(((byte)(15)))));
            this.lblPuntosInicio.Location = new System.Drawing.Point(166, 61);
            this.lblPuntosInicio.Name = "lblPuntosInicio";
            this.lblPuntosInicio.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblPuntosInicio.Size = new System.Drawing.Size(3, 23);
            this.lblPuntosInicio.TabIndex = 53;
            this.lblPuntosInicio.Text = ":";
            this.lblPuntosInicio.TextAlignment = System.Drawing.ContentAlignment.MiddleCenter;
            this.lblPuntosInicio.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // lblPuntosFin
            // 
            this.lblPuntosFin.AllowParentOverrides = false;
            this.lblPuntosFin.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.lblPuntosFin.AutoEllipsis = false;
            this.lblPuntosFin.Cursor = System.Windows.Forms.Cursors.Default;
            this.lblPuntosFin.CursorType = System.Windows.Forms.Cursors.Default;
            this.lblPuntosFin.Font = new System.Drawing.Font("Montserrat Alternates", 12F);
            this.lblPuntosFin.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(104)))), ((int)(((byte)(13)))), ((int)(((byte)(15)))));
            this.lblPuntosFin.Location = new System.Drawing.Point(377, 61);
            this.lblPuntosFin.Name = "lblPuntosFin";
            this.lblPuntosFin.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblPuntosFin.Size = new System.Drawing.Size(3, 23);
            this.lblPuntosFin.TabIndex = 57;
            this.lblPuntosFin.Text = ":";
            this.lblPuntosFin.TextAlignment = System.Drawing.ContentAlignment.MiddleCenter;
            this.lblPuntosFin.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txtFinMinutos
            // 
            this.txtFinMinutos.AcceptsReturn = false;
            this.txtFinMinutos.AcceptsTab = false;
            this.txtFinMinutos.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.txtFinMinutos.AnimationSpeed = 200;
            this.txtFinMinutos.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtFinMinutos.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtFinMinutos.AutoSizeHeight = true;
            this.txtFinMinutos.BackColor = System.Drawing.Color.White;
            this.txtFinMinutos.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtFinMinutos.BackgroundImage")));
            this.txtFinMinutos.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(158)))), ((int)(((byte)(31)))));
            this.txtFinMinutos.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtFinMinutos.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(158)))), ((int)(((byte)(31)))));
            this.txtFinMinutos.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(104)))), ((int)(((byte)(13)))), ((int)(((byte)(15)))));
            this.txtFinMinutos.BorderRadius = 1;
            this.txtFinMinutos.BorderThickness = 1;
            this.txtFinMinutos.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtFinMinutos.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtFinMinutos.DefaultFont = new System.Drawing.Font("Montserrat Alternates", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtFinMinutos.DefaultText = "";
            this.txtFinMinutos.FillColor = System.Drawing.Color.White;
            this.txtFinMinutos.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(104)))), ((int)(((byte)(13)))), ((int)(((byte)(15)))));
            this.txtFinMinutos.HideSelection = true;
            this.txtFinMinutos.IconLeft = null;
            this.txtFinMinutos.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtFinMinutos.IconPadding = 0;
            this.txtFinMinutos.IconRight = null;
            this.txtFinMinutos.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtFinMinutos.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.txtFinMinutos.Lines = new string[0];
            this.txtFinMinutos.Location = new System.Drawing.Point(388, 52);
            this.txtFinMinutos.Margin = new System.Windows.Forms.Padding(0);
            this.txtFinMinutos.MaxLength = 32767;
            this.txtFinMinutos.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtFinMinutos.Modified = false;
            this.txtFinMinutos.Multiline = false;
            this.txtFinMinutos.Name = "txtFinMinutos";
            stateProperties5.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(158)))), ((int)(((byte)(31)))));
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtFinMinutos.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtFinMinutos.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(158)))), ((int)(((byte)(31)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtFinMinutos.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(104)))), ((int)(((byte)(13)))), ((int)(((byte)(15)))));
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(104)))), ((int)(((byte)(13)))), ((int)(((byte)(15)))));
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtFinMinutos.OnIdleState = stateProperties8;
            this.txtFinMinutos.Padding = new System.Windows.Forms.Padding(3);
            this.txtFinMinutos.PasswordChar = '\0';
            this.txtFinMinutos.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.txtFinMinutos.PlaceholderText = "MM";
            this.txtFinMinutos.ReadOnly = false;
            this.txtFinMinutos.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtFinMinutos.SelectedText = "";
            this.txtFinMinutos.SelectionLength = 0;
            this.txtFinMinutos.SelectionStart = 0;
            this.txtFinMinutos.ShortcutsEnabled = true;
            this.txtFinMinutos.Size = new System.Drawing.Size(46, 40);
            this.txtFinMinutos.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.txtFinMinutos.TabIndex = 56;
            this.txtFinMinutos.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.txtFinMinutos.TextMarginBottom = 0;
            this.txtFinMinutos.TextMarginLeft = 0;
            this.txtFinMinutos.TextMarginTop = 0;
            this.txtFinMinutos.TextPlaceholder = "MM";
            this.txtFinMinutos.UseSystemPasswordChar = false;
            this.txtFinMinutos.WordWrap = true;
            // 
            // txtFinHoras
            // 
            this.txtFinHoras.AcceptsReturn = false;
            this.txtFinHoras.AcceptsTab = false;
            this.txtFinHoras.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.txtFinHoras.AnimationSpeed = 200;
            this.txtFinHoras.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtFinHoras.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtFinHoras.AutoSizeHeight = true;
            this.txtFinHoras.BackColor = System.Drawing.Color.White;
            this.txtFinHoras.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtFinHoras.BackgroundImage")));
            this.txtFinHoras.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(158)))), ((int)(((byte)(31)))));
            this.txtFinHoras.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtFinHoras.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(158)))), ((int)(((byte)(31)))));
            this.txtFinHoras.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(104)))), ((int)(((byte)(13)))), ((int)(((byte)(15)))));
            this.txtFinHoras.BorderRadius = 1;
            this.txtFinHoras.BorderThickness = 1;
            this.txtFinHoras.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtFinHoras.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtFinHoras.DefaultFont = new System.Drawing.Font("Montserrat Alternates", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtFinHoras.DefaultText = "";
            this.txtFinHoras.FillColor = System.Drawing.Color.White;
            this.txtFinHoras.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(104)))), ((int)(((byte)(13)))), ((int)(((byte)(15)))));
            this.txtFinHoras.HideSelection = true;
            this.txtFinHoras.IconLeft = null;
            this.txtFinHoras.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtFinHoras.IconPadding = 0;
            this.txtFinHoras.IconRight = null;
            this.txtFinHoras.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtFinHoras.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.txtFinHoras.Lines = new string[0];
            this.txtFinHoras.Location = new System.Drawing.Point(325, 52);
            this.txtFinHoras.Margin = new System.Windows.Forms.Padding(0);
            this.txtFinHoras.MaxLength = 32767;
            this.txtFinHoras.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtFinHoras.Modified = false;
            this.txtFinHoras.Multiline = false;
            this.txtFinHoras.Name = "txtFinHoras";
            stateProperties9.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(158)))), ((int)(((byte)(31)))));
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtFinHoras.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtFinHoras.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(158)))), ((int)(((byte)(31)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtFinHoras.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(104)))), ((int)(((byte)(13)))), ((int)(((byte)(15)))));
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(104)))), ((int)(((byte)(13)))), ((int)(((byte)(15)))));
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtFinHoras.OnIdleState = stateProperties12;
            this.txtFinHoras.Padding = new System.Windows.Forms.Padding(3);
            this.txtFinHoras.PasswordChar = '\0';
            this.txtFinHoras.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.txtFinHoras.PlaceholderText = "HH";
            this.txtFinHoras.ReadOnly = false;
            this.txtFinHoras.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtFinHoras.SelectedText = "";
            this.txtFinHoras.SelectionLength = 0;
            this.txtFinHoras.SelectionStart = 0;
            this.txtFinHoras.ShortcutsEnabled = true;
            this.txtFinHoras.Size = new System.Drawing.Size(46, 40);
            this.txtFinHoras.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.txtFinHoras.TabIndex = 54;
            this.txtFinHoras.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.txtFinHoras.TextMarginBottom = 0;
            this.txtFinHoras.TextMarginLeft = 0;
            this.txtFinHoras.TextMarginTop = 0;
            this.txtFinHoras.TextPlaceholder = "HH";
            this.txtFinHoras.UseSystemPasswordChar = false;
            this.txtFinHoras.WordWrap = true;
            // 
            // lblHoraFin
            // 
            this.lblHoraFin.AllowParentOverrides = false;
            this.lblHoraFin.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.lblHoraFin.AutoEllipsis = false;
            this.lblHoraFin.Cursor = System.Windows.Forms.Cursors.Default;
            this.lblHoraFin.CursorType = System.Windows.Forms.Cursors.Default;
            this.lblHoraFin.Font = new System.Drawing.Font("Montserrat Alternates", 12F);
            this.lblHoraFin.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(104)))), ((int)(((byte)(13)))), ((int)(((byte)(15)))));
            this.lblHoraFin.Location = new System.Drawing.Point(243, 61);
            this.lblHoraFin.Name = "lblHoraFin";
            this.lblHoraFin.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblHoraFin.Size = new System.Drawing.Size(72, 23);
            this.lblHoraFin.TabIndex = 55;
            this.lblHoraFin.Text = "Hora Fin:";
            this.lblHoraFin.TextAlignment = System.Drawing.ContentAlignment.MiddleCenter;
            this.lblHoraFin.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // btnCambiar
            // 
            this.btnCambiar.AllowAnimations = true;
            this.btnCambiar.AllowMouseEffects = true;
            this.btnCambiar.AllowToggling = false;
            this.btnCambiar.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.btnCambiar.AnimationSpeed = 200;
            this.btnCambiar.AutoGenerateColors = false;
            this.btnCambiar.AutoRoundBorders = false;
            this.btnCambiar.AutoSizeLeftIcon = true;
            this.btnCambiar.AutoSizeRightIcon = true;
            this.btnCambiar.BackColor = System.Drawing.Color.Transparent;
            this.btnCambiar.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(104)))), ((int)(((byte)(13)))), ((int)(((byte)(15)))));
            this.btnCambiar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnCambiar.BackgroundImage")));
            this.btnCambiar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnCambiar.ButtonText = "Cambiar";
            this.btnCambiar.ButtonTextMarginLeft = 0;
            this.btnCambiar.ColorContrastOnClick = 45;
            this.btnCambiar.ColorContrastOnHover = 45;
            this.btnCambiar.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnCambiar.CustomizableEdges = borderEdges1;
            this.btnCambiar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnCambiar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCambiar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCambiar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCambiar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnCambiar.Font = new System.Drawing.Font("Montserrat Alternates", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnCambiar.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(158)))), ((int)(((byte)(31)))));
            this.btnCambiar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCambiar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnCambiar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnCambiar.IconMarginLeft = 11;
            this.btnCambiar.IconPadding = 10;
            this.btnCambiar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCambiar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnCambiar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnCambiar.IconSize = 25;
            this.btnCambiar.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(158)))), ((int)(((byte)(31)))));
            this.btnCambiar.IdleBorderRadius = 15;
            this.btnCambiar.IdleBorderThickness = 1;
            this.btnCambiar.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(104)))), ((int)(((byte)(13)))), ((int)(((byte)(15)))));
            this.btnCambiar.IdleIconLeftImage = global::CapaPresentaciones.Properties.Resources.Guardar;
            this.btnCambiar.IdleIconRightImage = null;
            this.btnCambiar.IndicateFocus = false;
            this.btnCambiar.Location = new System.Drawing.Point(453, 53);
            this.btnCambiar.Name = "btnCambiar";
            this.btnCambiar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCambiar.OnDisabledState.BorderRadius = 15;
            this.btnCambiar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnCambiar.OnDisabledState.BorderThickness = 1;
            this.btnCambiar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCambiar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCambiar.OnDisabledState.IconLeftImage = null;
            this.btnCambiar.OnDisabledState.IconRightImage = null;
            this.btnCambiar.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(104)))), ((int)(((byte)(13)))), ((int)(((byte)(15)))));
            this.btnCambiar.onHoverState.BorderRadius = 15;
            this.btnCambiar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnCambiar.onHoverState.BorderThickness = 1;
            this.btnCambiar.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(158)))), ((int)(((byte)(31)))));
            this.btnCambiar.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(104)))), ((int)(((byte)(13)))), ((int)(((byte)(15)))));
            this.btnCambiar.onHoverState.IconLeftImage = global::CapaPresentaciones.Properties.Resources.Guardar_2;
            this.btnCambiar.onHoverState.IconRightImage = null;
            this.btnCambiar.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(158)))), ((int)(((byte)(31)))));
            this.btnCambiar.OnIdleState.BorderRadius = 15;
            this.btnCambiar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnCambiar.OnIdleState.BorderThickness = 1;
            this.btnCambiar.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(104)))), ((int)(((byte)(13)))), ((int)(((byte)(15)))));
            this.btnCambiar.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(158)))), ((int)(((byte)(31)))));
            this.btnCambiar.OnIdleState.IconLeftImage = global::CapaPresentaciones.Properties.Resources.Guardar;
            this.btnCambiar.OnIdleState.IconRightImage = null;
            this.btnCambiar.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(158)))), ((int)(((byte)(31)))));
            this.btnCambiar.OnPressedState.BorderRadius = 15;
            this.btnCambiar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnCambiar.OnPressedState.BorderThickness = 1;
            this.btnCambiar.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(104)))), ((int)(((byte)(13)))), ((int)(((byte)(15)))));
            this.btnCambiar.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(158)))), ((int)(((byte)(31)))));
            this.btnCambiar.OnPressedState.IconLeftImage = global::CapaPresentaciones.Properties.Resources.Guardar;
            this.btnCambiar.OnPressedState.IconRightImage = null;
            this.btnCambiar.Size = new System.Drawing.Size(160, 39);
            this.btnCambiar.TabIndex = 65;
            this.btnCambiar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnCambiar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnCambiar.TextMarginLeft = 0;
            this.btnCambiar.TextPadding = new System.Windows.Forms.Padding(12, 0, 0, 0);
            this.btnCambiar.UseDefaultRadiusAndThickness = true;
            this.btnCambiar.Click += new System.EventHandler(this.btnCambiar_Click);
            // 
            // P_HistorialAsistenciasDocentes
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(803, 463);
            this.Controls.Add(this.pnContenedor);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "P_HistorialAsistenciasDocentes";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Tabla de Docentes";
            ((System.ComponentModel.ISupportInitialize)(this.dgvDatos)).EndInit();
            this.pnContenedor.ResumeLayout(false);
            this.pnContenedor.PerformLayout();
            this.ResumeLayout(false);

		}

		#endregion
		private Bunifu.UI.WinForms.BunifuLabel lblTitulo;
		private Bunifu.UI.WinForms.BunifuImageButton btnCerrar;
		private Bunifu.UI.WinForms.BunifuTextBox txtBuscar;
		private Bunifu.UI.WinForms.BunifuDataGridView dgvDatos;
		private Bunifu.UI.WinForms.BunifuVScrollBar sbDatos;
		private Bunifu.UI.WinForms.BunifuPanel pnContenedor;
		private Bunifu.Framework.UI.BunifuElipse Bordeado;
		private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnAgregarD;
		private System.Windows.Forms.DataGridViewImageColumn btnEditar;
        public Bunifu.UI.WinForms.BunifuTextBox txtInicioHoras;
        private Bunifu.UI.WinForms.BunifuLabel lblHoraInicio;
        public Bunifu.UI.WinForms.BunifuTextBox txtInicioMinutos;
        private Bunifu.UI.WinForms.BunifuLabel lblPuntosFin;
        public Bunifu.UI.WinForms.BunifuTextBox txtFinMinutos;
        public Bunifu.UI.WinForms.BunifuTextBox txtFinHoras;
        private Bunifu.UI.WinForms.BunifuLabel lblHoraFin;
        private Bunifu.UI.WinForms.BunifuLabel lblPuntosInicio;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnCambiar;
    }
}